### ISSUE TITLE
api

### ISSUE THREAD

**Issue by szjawo** [devome/dockerfiles#70]

**Comment by szjawo** [comment]
另附nastool的日志


2023-01-25 07:03:32 stdout qbittorrentapi.exceptions.MissingRequiredParameters400Error
2023-01-25 07:03:32 stdout raise MissingRequiredParameters400Error()
2023-01-25 07:03:32 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 634, in _handle_error_responses
2023-01-25 07:03:32 stdout self._handle_error_responses(data, params, response)
2023-01-25 07:03:32 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 463, in _request
2023-01-25 07:03:32 stdout return self._request(**kwargs)
2023-01-25 07:03:32 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 401, in _request_manager
2023-01-25 07:03:32 stdout return self._request_manager(
2023-01-25 07:03:32 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 350, in _post
2023-01-25 07:03:32 stdout return self._post(_name=APINames.Torrents, _method="info", data=data, **kwargs)
2023-01-25 07:03:32 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/torrents.py", line 1663, in torrents_info
2023-01-25 07:03:32 stdout return func(client, *args, **kwargs)
2023-01-25 07:03:32 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 92, in wrapper
2023-01-25 07:03:32 stdout response = func(client, *args, **kwargs)
2023-01-25 07:03:32 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 164, in wrapper
2023-01-25 07:03:32 stdout return func(client, *args, **kwargs)
2023-01-25 07:03:32 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 119, in wrapper
2023-01-25 07:03:32 stdout torrents = self.qbc.torrents_info(torrent_hashes=ids, status_filter=status, tag=tag)
2023-01-25 07:03:32 stdout File "/nas-tools/app/downloader/client/qbittorrent.py", line 99, in get_torrents
2023-01-25 07:03:32 stdout Traceback (most recent call last):
2023-01-25 07:03:32 stdout Callstack:
2023-01-25 07:03:32 stdout Exception:
2023-01-25 07:03:29 stdout 2023-01-25 15:03:29,803 INFO: 【TorrentRemover】自动删种任务：1 获取符合处理条件种子数 0
2023-01-25 07:03:29 stdout qbittorrentapi.exceptions.MissingRequiredParameters400Error
2023-01-25 07:03:29 stdout raise MissingRequiredParameters400Error()
2023-01-25 07:03:29 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 634, in _handle_error_responses
2023-01-25 07:03:29 stdout self._handle_error_responses(data, params, response)
2023-01-25 07:03:29 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 463, in _request
2023-01-25 07:03:29 stdout return self._request(**kwargs)
2023-01-25 07:03:29 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 401, in _request_manager
2023-01-25 07:03:29 stdout return self._request_manager(
2023-01-25 07:03:29 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 350, in _post
2023-01-25 07:03:29 stdout return self._post(_name=APINames.Torrents, _method="info", data=data, **kwargs)
2023-01-25 07:03:29 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/torrents.py", line 1663, in torrents_info
2023-01-25 07:03:29 stdout return func(client, *args, **kwargs)
2023-01-25 07:03:29 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 92, in wrapper
2023-01-25 07:03:29 stdout response = func(client, *args, **kwargs)
2023-01-25 07:03:29 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 164, in wrapper
2023-01-25 07:03:29 stdout return func(client, *args, **kwargs)
2023-01-25 07:03:29 stdout File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 119, in wrapper
2023-01-25 07:03:29 stdout torrents = self.qbc.torrents_info(torrent_hashes=ids, status_filter=status, tag=tag)
2023-01-25 07:03:29 stdout File "/nas-tools/app/downloader/client/qbittorrent.py", line 99, in get_torrents
2023-01-25 07:03:29 stdout Traceback (most recent call last):
2023-01-25 07:03:29 stdout Callstack:
2023-01-25 07:03:29 stdout Exception:
2023-01-25 07:00:30 stdout 2023-01-25 15:00:30,135 INFO: 【Brush】任务 PTHOME保种 本次检查未删除下载任务
2023-01-25 07:00:29 stdout 2023-01-25 15:00:29,899 INFO: 【Brush】任务 M-Team刷流 本次检查未删除下载任务
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,844 INFO: /PTdownloads/act 的监控服务启动
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,836 INFO: /PTdownloads/教育 的监控服务启动
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,836 INFO: /private/课程 的监控服务启动
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,834 INFO: /special mark 的监控服务启动
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,804 INFO: /PTdownloads/综艺 的监控服务启动
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,804 INFO: /PTdownloads/动漫 的监控服务启动
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,803 INFO: /PTdownloads/电视剧 的监控服务启动
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,803 INFO: /PTdownloads/电影 的监控服务启动
2023-01-25 06:55:29 stdout get_login_wallpaper (trigger: interval[1:00:00], next run at: 2023-01-25 14:55:29 CST)
2023-01-25 06:55:29 stdout MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
2023-01-25 06:55:29 stdout Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
2023-01-25 06:55:29 stdout Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2023-01-25 14:56:29 CST)
2023-01-25 06:55:29 stdout Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
2023-01-25 06:55:29 stdout Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
2023-01-25 06:55:29 stdout MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
2023-01-25 06:55:29 stdout MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
2023-01-25 06:55:29 stdout DoubanSync.sync (trigger: interval[12:00:00], pending)
2023-01-25 06:55:29 stdout Subscribe.subscribe_search_all (trigger: interval[6:00:00], pending)
2023-01-25 06:55:29 stdout Sites.signin (trigger: cron[hour='8', minute='1'], pending)
2023-01-25 06:55:29 stdout Pending jobs:
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,793 INFO: 媒体库同步服务启动
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,793 INFO: 豆瓣同步服务启动
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,792 INFO: 订阅定时搜索服务启动
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,791 INFO: 站点自动签到服务启动
2023-01-25 06:55:29 stdout 2023-01-25 14:55:29,768 INFO: 自动删种服务启动
2023-01-25 06:55:29 stdout TorrentRemover.auto_remove_torrents (trigger: interval[0:10:00], pending)

**Comment by devome** [comment]
qb的api接口是官方的，我没有动过任何内容，如果有差异那也是官方各版本之间的差异。可以试试使用最新版qb。
